### model
model_name_or_path: /Tmp/dingqian/huggingface/Meta-Llama-3-70B-Instruct
quantization_bit: 4
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: mp
template: llama3
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/rech/dingqian/intel/llama-factory/mp_70B_1
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 10.
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
eval_dataset: mp_val
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

# resume_from_checkpoint: /data/rech/dingqian/intel/llama-factory/mp_70B_1/checkpoint-500

## Deepspeed
# low_cpu_mem_usage: False
# deepspeed: examples/deepspeed/ds_z0_config.json
# cutoff_len: 2048
