### model
model_name_or_path: /root/autodl-tmp/Llama-2-7b-chat-hf

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: mp
template: llama2
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /root/autodl-tmp/llama-factory/mp_llama2_1
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 10.
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
# resume_from_checkpoint: /data/rech/dingqian/intel/llama-factory/mp_1/checkpoint-1500

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500